import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);

async function run() {
    // 1. Delete the 3 new repuestos
    const { error: delErr } = await supabase.from('products').delete().in('name', ['Repuesto Hojas A4', 'Repuesto Hojas A5', 'Repuesto Fichas N° 3']);
    if (delErr) console.error("Error deleting 3 repuestos", delErr);

    // 2. Delete the duplicate Obelisco notebook (Cuaderno A4 Pink Buenos Aires)
    const { error: delObelisco } = await supabase.from('products').delete().eq('name', 'Cuaderno A4 Pink Buenos Aires sistema de discos');
    if (delObelisco) console.error("Error deleting Obelisco", delObelisco);

    // 3. Re-insert the 18 repuestos
    const repuestos = [
        { name: "Repuesto Hojas Rayadas A4 (Blanco)", category: "Repuestos", short_description: "Repuesto A4, 100 hojas rayadas, papel blanco 80gr.", description: "Repuesto para cuaderno A4 sistema de discos. Contiene 100 hojas rayadas en papel blanco de 80 gr de alta calidad.", price: 16000, image_url: "/images/repuestos_svg/a4_blanco_rayadas.svg", gallery: ["/images/repuestos_svg/a4_blanco_rayadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Rayadas A4 (Natural)", category: "Repuestos", short_description: "Repuesto A4, 100 hojas rayadas, papel natural 80gr.", description: "Repuesto para cuaderno A4 sistema de discos. Contiene 100 hojas rayadas en papel natural ecológico de 80 gr.", price: 16000, image_url: "/images/repuestos_svg/a4_natural_rayadas.svg", gallery: ["/images/repuestos_svg/a4_natural_rayadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Lisas A4 (Blanco)", category: "Repuestos", short_description: "Repuesto A4, 100 hojas lisas, papel blanco 80gr.", description: "Repuesto para cuaderno A4 sistema de discos. Contiene 100 hojas lisas en papel blanco de 80 gr de alta calidad.", price: 16000, image_url: "/images/repuestos_svg/a4_blanco_lisas.svg", gallery: ["/images/repuestos_svg/a4_blanco_lisas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Lisas A4 (Natural)", category: "Repuestos", short_description: "Repuesto A4, 100 hojas lisas, papel natural 80gr.", description: "Repuesto para cuaderno A4 sistema de discos. Contiene 100 hojas lisas en papel natural ecológico de 80 gr.", price: 16000, image_url: "/images/repuestos_svg/a4_natural_lisas.svg", gallery: ["/images/repuestos_svg/a4_natural_lisas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Cuadriculadas A4 (Blanco)", category: "Repuestos", short_description: "Repuesto A4, 100 hojas cuadriculadas, papel blanco 80gr.", description: "Repuesto para cuaderno A4 sistema de discos. Contiene 100 hojas cuadriculadas en papel blanco de 80 gr de alta calidad.", price: 16000, image_url: "/images/repuestos_svg/a4_blanco_cuadriculadas.svg", gallery: ["/images/repuestos_svg/a4_blanco_cuadriculadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Cuadriculadas A4 (Natural)", category: "Repuestos", short_description: "Repuesto A4, 100 hojas cuadriculadas, papel natural 80gr.", description: "Repuesto para cuaderno A4 sistema de discos. Contiene 100 hojas cuadriculadas en papel natural ecológico de 80 gr.", price: 16000, image_url: "/images/repuestos_svg/a4_natural_cuadriculadas.svg", gallery: ["/images/repuestos_svg/a4_natural_cuadriculadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Punteadas A4 (Blanco)", category: "Repuestos", short_description: "Repuesto A4, 100 hojas punteadas, papel blanco 80gr.", description: "Repuesto para cuaderno A4 sistema de discos. Contiene 100 hojas punteadas en papel blanco de 80 gr de alta calidad.", price: 16000, image_url: "/images/repuestos_svg/a4_blanco_punteadas.svg", gallery: ["/images/repuestos_svg/a4_blanco_punteadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Punteadas A4 (Natural)", category: "Repuestos", short_description: "Repuesto A4, 100 hojas punteadas, papel natural 80gr.", description: "Repuesto para cuaderno A4 sistema de discos. Contiene 100 hojas punteadas en papel natural ecológico de 80 gr.", price: 16000, image_url: "/images/repuestos_svg/a4_natural_punteadas.svg", gallery: ["/images/repuestos_svg/a4_natural_punteadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Rayadas A5 (Blanco)", category: "Repuestos", short_description: "Repuesto A5, 100 hojas rayadas, papel blanco 90gr.", description: "Repuesto para cuaderno A5 sistema de discos. Contiene 100 hojas rayadas en papel blanco de 90 gr de alta calidad.", price: 13500, image_url: "/images/repuestos_svg/a5_blanco_rayadas.svg", gallery: ["/images/repuestos_svg/a5_blanco_rayadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Rayadas A5 (Natural)", category: "Repuestos", short_description: "Repuesto A5, 100 hojas rayadas, papel natural 90gr.", description: "Repuesto para cuaderno A5 sistema de discos. Contiene 100 hojas rayadas en papel natural ecológico de 90 gr.", price: 13500, image_url: "/images/repuestos_svg/a5_natural_rayadas.svg", gallery: ["/images/repuestos_svg/a5_natural_rayadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Lisas A5 (Blanco)", category: "Repuestos", short_description: "Repuesto A5, 100 hojas lisas, papel blanco 90gr.", description: "Repuesto para cuaderno A5 sistema de discos. Contiene 100 hojas lisas en papel blanco de 90 gr de alta calidad.", price: 13500, image_url: "/images/repuestos_svg/a5_blanco_lisas.svg", gallery: ["/images/repuestos_svg/a5_blanco_lisas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Lisas A5 (Natural)", category: "Repuestos", short_description: "Repuesto A5, 100 hojas lisas, papel natural 90gr.", description: "Repuesto para cuaderno A5 sistema de discos. Contiene 100 hojas lisas en papel natural ecológico de 90 gr.", price: 13500, image_url: "/images/repuestos_svg/a5_natural_lisas.svg", gallery: ["/images/repuestos_svg/a5_natural_lisas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Cuadriculadas A5 (Blanco)", category: "Repuestos", short_description: "Repuesto A5, 100 hojas cuadriculadas, papel blanco 90gr.", description: "Repuesto para cuaderno A5 sistema de discos. Contiene 100 hojas cuadriculadas en papel blanco de 90 gr de alta calidad.", price: 13500, image_url: "/images/repuestos_svg/a5_blanco_cuadriculadas.svg", gallery: ["/images/repuestos_svg/a5_blanco_cuadriculadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Cuadriculadas A5 (Natural)", category: "Repuestos", short_description: "Repuesto A5, 100 hojas cuadriculadas, papel natural 90gr.", description: "Repuesto para cuaderno A5 sistema de discos. Contiene 100 hojas cuadriculadas en papel natural ecológico de 90 gr.", price: 13500, image_url: "/images/repuestos_svg/a5_natural_cuadriculadas.svg", gallery: ["/images/repuestos_svg/a5_natural_cuadriculadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Punteadas A5 (Blanco)", category: "Repuestos", short_description: "Repuesto A5, 100 hojas punteadas, papel blanco 90gr.", description: "Repuesto para cuaderno A5 sistema de discos. Contiene 100 hojas punteadas en papel blanco de 90 gr de alta calidad.", price: 13500, image_url: "/images/repuestos_svg/a5_blanco_punteadas.svg", gallery: ["/images/repuestos_svg/a5_blanco_punteadas.svg"], is_best_seller: false },
        { name: "Repuesto Hojas Punteadas A5 (Natural)", category: "Repuestos", short_description: "Repuesto A5, 100 hojas punteadas, papel natural 90gr.", description: "Repuesto para cuaderno A5 sistema de discos. Contiene 100 hojas punteadas en papel natural ecológico de 90 gr.", price: 13500, image_url: "/images/repuestos_svg/a5_natural_punteadas.svg", gallery: ["/images/repuestos_svg/a5_natural_punteadas.svg"], is_best_seller: false },
        { name: "Repuesto Fichas N° 3 (Blanco)", category: "Repuestos", short_description: "100 fichas rayadas para fichero N° 3, papel blanco 120gr.", description: "Repuesto de fichero N° 3, contiene 100 fichas rayadas en papel blanco de 120 gr.", price: 10900, image_url: "/images/repuestos_svg/fichas_blanco_rayadas.svg", gallery: ["/images/repuestos_svg/fichas_blanco_rayadas.svg"], is_best_seller: false },
        { name: "Repuesto Fichas N° 3 (Natural)", category: "Repuestos", short_description: "100 fichas rayadas para fichero N° 3, papel natural 120gr.", description: "Repuesto de fichero N° 3, contiene 100 fichas rayadas en papel natural ecológico de 120 gr.", price: 10900, image_url: "/images/repuestos_svg/fichas_natural_rayadas.svg", gallery: ["/images/repuestos_svg/fichas_natural_rayadas.svg"], is_best_seller: false }
    ];

    const { error: insErr } = await supabase.from('products').insert(repuestos);
    if (insErr) console.error("Error inserting 18 repuestos", insErr);
    else console.log("DB restored correctly");
}

run();
